version: '3.7'
services:
  api:
    build: .
    image: final-project-cass-squad-api
    restart: always
    networks:
      - redis
    ports:
      - 8000:8000
    environment:
      MONGO_DATABASE: 'cass'
      MONGO_USER: 'cass'
      MONGO_PASSWORD: 'hunter2'
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - redis
  mongodb:
    ports:
      - 27017:27017
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./db-init/01-db-init.js:/docker-entrypoint-initdb.d/01-db-init.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'hunter2'
      MONGO_INITDB_DATABASE: 'cass'
      MONGO_USER: 'cass'
      MONGO_PASSWORD: 'hunter2'

volumes:
  mongo-data:
networks:
  redis:
    driver: bridge
